 export const data =  [
  {
    id: 0,
    account: "John's Happy Campers",
    sector: "Commercial",
    engagement: "Data Migration",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Frontend Engineer (React)",
    location: "Remote",
    revenue: "£100,000,000",
    forecast: "Firm (100%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 1,
    account: "Willow's Oil Company",
    sector: "Commercial",
    engagement: "Data Analysis",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Data Engineer ",
    location: "Remote",
    revenue: "£100,000,000,000",
    forecast: "Firm (100%)",
    notes: "Test",
    grade: "Principle"
  },
  {
    id: 2,
    account: "Secret Spy Project",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "New Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Frontend Engineer (React)",
    location: "Remote",
    revenue: "£100",
    forecast: "Firm (90%) Working at Risk",
    notes: "Don't tell anyone",
    grade: "E0"
  },
  {
    id: 3,
    account: "Big Pharma Limited",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£100,000,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
]


