 export const data =  [
  {
    id: 0,
    account: "John's Happy Campers",
    sector: "Commercial",
    engagement: "Data Migration",
    startdate: "25/10/2023",
    enddate: "30/01/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Frontend Engineer (React)",
    location: "Remote",
    revenue: "£100,000,000",
    forecast: "Firm (100%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 1,
    account: "Willow's Oil Company",
    sector: "Commercial",
    engagement: "Data Analysis",
    startdate: "25/01/2024",
    enddate: "30/04/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Data Engineer ",
    location: "Remote",
    revenue: "£100,000,000,000",
    forecast: "Firm (100%)",
    notes: "Test",
    grade: "Principle"
  },
  {
    id: 2,
    account: "Secret Spy Project",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/10/2023",
    enddate: "30/11/2023",
    channel: "New Client",
    owner: "John Connolly",
    originator: "Tiff Henebury",
    role: "Frontend Engineer (React)",
    location: "Remote",
    revenue: "£100",
    forecast: "Firm (90%) Working at Risk",
    notes: "Don't tell anyone",
    grade: "E0"
  },
  {
    id: 3,
    account: "Johns Company",
    sector: "Financial Services",
    engagement: "Platfrom Build",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£100,000,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Big Toy Co",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/02/2024",
    enddate: "30/05/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£300,000,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Lottery Winners Fund",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/10/2023",
    enddate: "30/12/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£10,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Space mission",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/03/2024",
    enddate: "30/09/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£150,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Large Banking Group",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/10/2023",
    enddate: "30/09/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£1000,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Big Bakery Chain",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/09/2023",
    enddate: "30/09/2023",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£300,000,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
  {
    id: 3,
    account: "Pub Chain",
    sector: "Public Sector",
    engagement: "Data Analysis",
    startdate: "20/11/2023",
    enddate: "30/09/2024",
    channel: "Existing Client",
    owner: "John Connolly",
    originator: "Dr Hillary Jones",
    role: "Data Engineer",
    location: "Remote",
    revenue: "£100,000",
    forecast: "Firm (90%)",
    notes: "Test",
    grade: "E0"
  },
 
 ]


